from honeypots import QDNSServer, QFTPServer, QHTTPProxyServer, QHTTPSServer, QHTTPServer, QIMAPServer, QMysqlServer, QPOP3Server, QPostgresServer, QRedisServer, QSMBServer, QSMTPServer, QSOCKS5Server, QSSHServer, QTelnetServer, QVNCServer, QElasticServer, QMSSQLServer, clean_all
from time import sleep

print("Testing QFTPServer")
qftpserver = QFTPServer()
qftpserver.run_server(process=True, auto=True)
sleep(2)
qftpserver.test_server()
qftpserver.kill_server()

print("Testing QIMAPServer")
qimapserver = QIMAPServer()
qimapserver.run_server(process=True, auto=True)
sleep(2)
qimapserver.test_server()
qimapserver.kill_server()

print("Testing QMysqlServer")
qmysqlserver = QMysqlServer()
qmysqlserver.run_server(process=True, auto=True)
sleep(2)
qmysqlserver.test_server()
qmysqlserver.kill_server()

print("Testing QTPOP3Server")
qpop3server = QPOP3Server()
qpop3server.run_server(process=True, auto=True)
sleep(2)
qpop3server.test_server()
qpop3server.kill_server()

print("Testing QPostgresServer")
qpostgresserver = QPostgresServer()
qpostgresserver.run_server(process=True, auto=True)
sleep(2)
qpostgresserver.test_server()
qpostgresserver.kill_server()

print("Testing QRedisServer")
qredisserver = QRedisServer()
qredisserver.run_server(process=True, auto=True)
sleep(2)
qredisserver.test_server()
qredisserver.kill_server()

print("Testing QElasticServer")
qelasticserver = QElasticServer()
qelasticserver.run_server(process=True, auto=True)
sleep(2)
qelasticserver.test_server()
qelasticserver.kill_server()

print("Testing QMSSQLServer")
qmssqlserver = QMSSQLServer()
qmssqlserver.run_server(process=True, auto=True)
sleep(2)
qmssqlserver.test_server()
qmssqlserver.kill_server()

print("Testing QDNSServer")
qdnsserver = QDNSServer()
qdnsserver.run_server(process=True, auto=True)
sleep(2)
qdnsserver.test_server()
qdnsserver.kill_server()

print("Testing QHTTPProxyServer")
qhttpproxyserver = QHTTPProxyServer()
qhttpproxyserver.run_server(process=True, auto=True)
sleep(2)
qhttpproxyserver.test_server()
qhttpproxyserver.kill_server()

print("Testing QHTTPServer")
qhttpserver = QHTTPServer()
qhttpserver.run_server(process=True, auto=True)
sleep(2)
qhttpserver.test_server()
qhttpserver.kill_server()

print("Testing QHTTPSServer")
qhttpsserver = QHTTPSServer()
qhttpsserver.run_server(process=True, auto=True)
sleep(2)
qhttpsserver.test_server()
qhttpsserver.kill_server()

print("Testing QSMBServer")
qsmbserver = QSMBServer()
qsmbserver.run_server(process=True, auto=True)
sleep(2)
qsmbserver.test_server()
qsmbserver.kill_server()

print("Testing QSMTPServer")
qsmtpserver = QSMTPServer()
qsmtpserver.run_server(process=True, auto=True)
sleep(2)
qsmtpserver.test_server()
qsmtpserver.kill_server()

print("Testing QSOCKS5Server")
qsocks5server = QSOCKS5Server()
qsocks5server.run_server(process=True, auto=True)
sleep(2)
qsocks5server.test_server()
qsocks5server.kill_server()

print("Testing QSSHServer")
qsshserver = QSSHServer()
qsshserver.run_server(process=True, auto=True)
sleep(2)
qsshserver.test_server()
qsshserver.kill_server()

print("Testing QTelnetServer")
qtelnetserver = QTelnetServer()
qtelnetserver.run_server(process=True, auto=True)
sleep(2)
qtelnetserver.test_server()
qtelnetserver.kill_server()

print("Testing QVNCServer")
qvncserver = QVNCServer()
qvncserver.run_server(process=True, auto=True)
sleep(2)
qvncserver.test_server()
qvncserver.kill_server()

clean_all()
